name: Yarn Install

description: Install Yarn v4 and run yarn install with optimized caching.

inputs:
  working_directory:
    description: The directory to install dependencies in.
    required: false
    default: "."

runs:
  using: "composite"
  steps:
    - name: Install Yarn v4
      shell: bash
      run: |
        corepack enable
        corepack prepare yarn@4.6.0 --activate
        # Ensure we're using the correct version
        yarn --version

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 22
        # Don't use setup-node cache for Yarn v4 Berry - it doesn't work well

    - name: Get Yarn cache directory
      id: yarn-cache-dir
      shell: bash
      run: echo "dir=$(yarn config get cacheFolder)" >> $GITHUB_OUTPUT

    - name: Cache Yarn dependencies
      uses: actions/cache@v4
      with:
        path: |
          ${{ steps.yarn-cache-dir.outputs.dir }}
          .yarn/cache
          .yarn/install-state.gz
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-

    - name: Install dependencies
      uses: nick-fields/retry@v3
      with:
        timeout_minutes: 10
        max_attempts: 3
        retry_wait_seconds: 5
        command: yarn install --immutable
