export const SELFRICA_COUNTRY_INDEX = 0;
export const SELFRICA_COUNTRY_LENGTH = 3;

export const SELFRICA_ID_TYPE_INDEX = SELFRICA_COUNTRY_INDEX + SELFRICA_COUNTRY_LENGTH;
export const SELFRICA_ID_TYPE_LENGTH = 27;

export const SELFRICA_ID_NUMBER_INDEX = SELFRICA_ID_TYPE_INDEX + SELFRICA_ID_TYPE_LENGTH;
export const SELFRICA_ID_NUMBER_LENGTH = 20;

export const SELFRICA_ISSUANCE_DATE_INDEX = SELFRICA_ID_NUMBER_INDEX + SELFRICA_ID_NUMBER_LENGTH;
export const SELFRICA_ISSUANCE_DATE_LENGTH = 8;

export const SELFRICA_EXPIRY_DATE_INDEX = SELFRICA_ISSUANCE_DATE_INDEX + SELFRICA_ISSUANCE_DATE_LENGTH;
export const SELFRICA_EXPIRY_DATE_LENGTH = 8;

export const SELFRICA_FULL_NAME_INDEX = SELFRICA_EXPIRY_DATE_INDEX + SELFRICA_EXPIRY_DATE_LENGTH;
export const SELFRICA_FULL_NAME_LENGTH = 40;

export const SELFRICA_DOB_INDEX = SELFRICA_FULL_NAME_INDEX + SELFRICA_FULL_NAME_LENGTH;
export const SELFRICA_DOB_LENGTH = 8;

export const SELFRICA_PHOTO_HASH_INDEX = SELFRICA_DOB_INDEX + SELFRICA_DOB_LENGTH;
export const SELFRICA_PHOTO_HASH_LENGTH = 32;

export const SELFRICA_PHONE_NUMBER_INDEX = SELFRICA_PHOTO_HASH_INDEX + SELFRICA_PHOTO_HASH_LENGTH;
export const SELFRICA_PHONE_NUMBER_LENGTH = 12;

export const SELFRICA_DOCUMENT_INDEX = SELFRICA_PHONE_NUMBER_INDEX + SELFRICA_PHONE_NUMBER_LENGTH;
export const SELFRICA_DOCUMENT_LENGTH = 2;

export const SELFRICA_GENDER_INDEX = SELFRICA_DOCUMENT_INDEX + SELFRICA_DOCUMENT_LENGTH;
export const SELFRICA_GENDER_LENGTH = 6;

export const SELFRICA_ADDRESS_INDEX = SELFRICA_GENDER_INDEX + SELFRICA_GENDER_LENGTH;
export const SELFRICA_ADDRESS_LENGTH = 100;

export const SELFRICA_MAX_LENGTH = SELFRICA_ADDRESS_INDEX + SELFRICA_ADDRESS_LENGTH;

// ------------------------------
// Public Signals
// ------------------------------
export const SELFRICA_PUBLIC_SIGNALS_ATTESTATION_ID = 0;

export const SELFRICA_PUBLIC_SIGNALS_REVEALED_DATA_PACKED = 1;
export const SELFRICA_PUBLIC_SIGNALS_REVEALED_DATA_PACKED_LENGTH = 9;

export const SELFRICA_PUBLIC_SIGNALS_FORBIDDEN_COUNTRIES_PACKED = 10;
export const SELFRICA_PUBLIC_SIGNALS_FORBIDDEN_COUNTRIES_PACKED_LENGTH = 4;

export const SELFRICA_PUBLIC_SIGNALS_IDENTITY_COMMITMENT = 14;
export const SELFRICA_PUBLIC_SIGNALS_NULLIFIER = 15;

export const SELFRICA_PUBLIC_SIGNALS_PUBKEY = 16;
export const SELFRICA_PUBLIC_SIGNALS_PUBKEY_LENGTH = 17;

export const SELFRICA_PUBLIC_SIGNALS_SCOPE = 33;
export const SELFRICA_PUBLIC_SIGNALS_USER_IDENTIFIER = 34;

export const SELFRICA_PUBLIC_SIGNALS_CURRENT_DATE = 35;
export const SELFRICA_PUBLIC_SIGNALS_CURRENT_DATE_LENGTH = 8;

export const SELFRICA_PUBLIC_SIGNALS_OFAC_NAME_DOB_SMT_ROOT = 43;
export const SELFRICA_PUBLIC_SIGNALS_OFAC_NAME_YOB_SMT_ROOT = 44;
